### ISSUE TITLE
How to use Promise to send request to server in reducer modules

### ISSUE THREAD

**Issue by alirezavalizade** [LeoLeBras/react-native-redux-starter-kit#21]
Before Im working this starter with react native,Im worked with [this react starter](https://github.com/erikras/react-redux-universal-hot-example) And I can easily use Promises in my reducer modules like this : 

```
export function load() {
  return {
    types: [LOAD, LOAD_SUCCESS, LOAD_FAIL],
    promise: (client) => client.get('/loadAuth')
  };
}
```

but I dont know how to send request like this in this starter...Thanks

**Comment by CharlesMangwa** [comment]
Hi @alirezavalizade! You can't send this kind of request so far with `react-redux-starter-kit`. 
The reason is this missing middleware that you can find in [`react-redux-universal-hot-example`](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/redux/middleware/clientMiddleware.js):

``` js
export default function clientMiddleware(client) {
  return ({dispatch, getState}) => {
    return next => action => {
      if (typeof action === 'function') {
        return action(dispatch, getState);
      }

      const { promise, types, ...rest } = action;
      if (!promise) {
        return next(action);
      }

      const [REQUEST, SUCCESS, FAILURE] = types;
      next({...rest, type: REQUEST});

      const actionPromise = promise(client);
      actionPromise.then(
        (result) => next({...rest, result, type: SUCCESS}),
        (error) => next({...rest, error, type: FAILURE})
      ).catch((error)=> {
        console.error('MIDDLEWARE ERROR:', error);
        next({...rest, error, type: FAILURE});
      });

      return actionPromise;
    };
  };
}
```

However, we're working on our next update which should be release today or tomorrow, and will include this middleware. Stay tunned! 😃🎉

**Comment by CharlesMangwa** [comment]
Closing issue #21
